name: Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  generation_tag:
    name: Generation Tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Create Tag
        id: create_tag
        run: |
          git tag v1.0.0
          git push origin v1.0.0

  build:
    name: Build binary
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

#      - name: Generate installation access token for middle-ci app
#        id: generate-token
#        uses: actions/create-github-app-token@v1
#        with:
#          app-id: ${{ secrets.MIDDLE_CI_APP_ID }}
#          private-key: ${{ secrets.MIDDLE_CI_APP_PRIVATE_KEY }}
#          owner: ${{ github.repository_owner }}
#
#      - name: Configure Authentication
#        run: |
#          export GOPRIVATE=github.com/cyberandao
#          git config --global url.https://x-access-token:${{ steps.generate-token.outputs.token }}@github.com/cyberandao.insteadOf https://github.com/cyberandao

      - name: Release build
        run: echo 1

      - name: Calculate checksum and rename binary
        run: echo $(shasum -a 256 README.md | cut -f1 -d' ') >${{ github.event.repository.name }}.sha256sum

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: README.md
          path: README.md

      - name: Upload checksum of artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}.sha256sum
          path: ${{ github.event.repository.name }}.sha256sum

  release:
    name: Release artifacts
    needs: [ generation_tag, build ]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3

      - name: Publish release
        uses: softprops/action-gh-release@v1
        with:
          name: "Release v1.0.0"
          generate_release_notes: true
          files: |
            **/${{ github.event.repository.name }}-*
